apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-tcp
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: tcp
    port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
