apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  name: cluster-network
  namespace: nginx-https
spec:
  networks:
  - cidr: 0.0.0.0/0
---
apiVersion: policy.linkerd.io/v1beta2
kind: Server
metadata:
  name: nginx
  namespace: nginx-https
spec:
  podSelector:
    matchLabels:
      app: nginx
  port: 80
  proxyProtocol: opaque
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: nginx
  namespace: nginx-https
spec:
  requiredAuthenticationRefs:
  - group: policy.linkerd.io
    kind: NetworkAuthentication
    name: cluster-network
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: nginx
