apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-https
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
